# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9r32rigwjN6C-KGmKwFq_Oh8wIhHbmI

**Random Forest For Data Analysis - Group 2 Final Project**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# -----------------------------
# Load data
# -----------------------------
df = pd.read_csv("cleaned_canada.csv")

# Target + features
X = df.drop(columns=["Price"])
y = df["Price"]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Identify column types
categorical_cols = X.select_dtypes(include=["object"]).columns
numeric_cols = X.select_dtypes(exclude=["object"]).columns

# -----------------------------
# Baseline preprocessing
# -----------------------------
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

# -----------------------------
# Baseline Random Forest
# -----------------------------
rf_baseline = RandomForestRegressor(
    n_estimators=100,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

model_baseline = Pipeline(steps=[
    ("preprocess", preprocess),
    ("rf", rf_baseline)
])

# Train baseline model
model_baseline.fit(X_train, y_train)

# Predict
y_pred_base = model_baseline.predict(X_test)

# Baseline metrics
baseline_rmse = np.sqrt(mean_squared_error(y_test, y_pred_base))
baseline_mae = mean_absolute_error(y_test, y_pred_base)
baseline_r2 = r2_score(y_test, y_pred_base)

print("=== BASELINE RANDOM FOREST ===")
print("RMSE:", baseline_rmse)
print("MAE:", baseline_mae)
print("R2:", baseline_r2)

# Extract feature importances
importances = model_baseline.named_steps["rf"].feature_importances_
feature_names = model_baseline.named_steps["preprocess"].get_feature_names_out()

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance")

# Columns with <1% importance
low_imp = importance_df[importance_df["importance"] < 0.01]

# Convert back to original column names
cols_to_drop = [f.split("__")[1] for f in low_imp["feature"]]

print("\nColumns to drop (<1% importance):")
print(cols_to_drop)

df_reduced = df.drop(columns=cols_to_drop)

# New feature/target split
X2 = df_reduced.drop(columns=["Price"])
y2 = df_reduced["Price"]

# New train/test split
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.2, random_state=42
)

# Rebuild column lists
categorical_cols2 = X2.select_dtypes(include=["object"]).columns
numeric_cols2 = X2.select_dtypes(exclude=["object"]).columns

# Preprocessing for reduced dataset
preprocess2 = ColumnTransformer(
    transformers=[
        ("cat", OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_cols2),
        ("num", "passthrough", numeric_cols2)
    ]
)

# Tuned Random Forest
rf_tuned = RandomForestRegressor(
    n_estimators=100,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=100,
    n_jobs=-1
)

model_tuned = Pipeline(steps=[
    ("preprocess", preprocess2),
    ("rf", rf_tuned)
])

# Train tuned model
model_tuned.fit(X2_train, y2_train)

# Predict
y_pred_tuned = model_tuned.predict(X2_test)

# Tuned metrics
tuned_rmse = np.sqrt(mean_squared_error(y2_test, y_pred_tuned))
tuned_mae = mean_absolute_error(y2_test, y_pred_tuned)
tuned_r2 = r2_score(y2_test, y_pred_tuned)

print("\n=== TUNED RANDOM FOREST (REDUCED FEATURES) ===")
print("RMSE:", tuned_rmse)
print("MAE:", tuned_mae)
print("R2:", tuned_r2)

comparison = pd.DataFrame({
    "Model": ["Baseline RF", "Tuned RF (Reduced Features)"],
    "RMSE": [baseline_rmse, tuned_rmse],
    "MAE": [baseline_mae, tuned_mae],
    "R2": [baseline_r2, tuned_r2]
})

print("\n=== MODEL COMPARISON ===")
print(comparison)

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))
plt.scatter(y2_test, y_pred_tuned, alpha=0.4)
plt.plot([y2_test.min(), y2_test.max()], [y2_test.min(), y2_test.max()], 'r--')
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Prices (Tuned Random Forest)")
plt.show()

residuals = y2_test - y_pred_tuned

plt.figure(figsize=(10, 6))
plt.scatter(y_pred_tuned, residuals, alpha=0.4)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel("Predicted Price")
plt.ylabel("Residual (Actual - Predicted)")
plt.title("Residual Plot (Tuned Random Forest)")
plt.show()

importances = model_tuned.named_steps["rf"].feature_importances_
feature_names = model_tuned.named_steps["preprocess"].get_feature_names_out()

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(importance_df["feature"], importance_df["importance"])
plt.gca().invert_yaxis()
plt.xlabel("Importance")
plt.title("Feature Importance (Tuned Random Forest)")
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(residuals, bins=40, edgecolor='black')
plt.title("Distribution of Prediction Errors")
plt.xlabel("Error (Actual - Predicted)")
plt.ylabel("Frequency")
plt.show()

# Predictions for training and test sets
pred_train = model_tuned.predict(X2_train)
pred_test = model_tuned.predict(X2_test)

# Combine actual + predicted into one dataframe
df_plot = pd.DataFrame({
    "Actual": pd.concat([y2_train, y2_test]),
    "Predicted": pd.concat([pd.Series(pred_train, index=y2_train.index),
                            pd.Series(pred_test, index=y2_test.index)])
}).sort_index()

sample_size = 300  # try 100, 200, 500 depending on clarity
df_sample = df_plot.sample(sample_size, random_state=42).sort_index()

plt.figure(figsize=(12, 5))

plt.plot(df_sample.index, df_sample["Actual"], label="Actual", color="C0")
plt.plot(df_sample.index, df_sample["Predicted"], label="Predicted", color="C3")

plt.xlabel("Index")
plt.ylabel("Price")
plt.title(f"Actual vs Predicted (Sample of {sample_size}) — Random Forest")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.5)

plt.show()