# -*- coding: utf-8 -*-
"""Group 2 Project - Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0hclTNbSuEkZkiQLoM_AQCmSiNkG5C0
"""

#Data Selection and Multiple Linear Regression Model
#This section consists of: data preparation, data cleaning,
#exploratory data analysis, and a Multiple Linear Regression Model
#to predice housing prices in Canada

import pandas as pd
import numpy as np

#Dataset loading
df= pd.read_csv("/content/cleaned_canada.csv")

#check the dataset size
df.shape

#check headers to understand how the dataset looks
df.head()

#Checking dataset to identify data types and the number of non-null observations
df.info()

#Identify Missing Values
#Display missing values from highest to lowest
missing_values = df.isnull().sum().sort_values(ascending=False)
print(missing_values)

#Percentage of Missing Values
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage.sort_values(ascending=False)

"""Variables with high percentage of missing variables could not provide reliable information to the model, so we decided to delete columns with more than 50% of missing values."""

# Columns with more than 50% missing values are dropped
# They don't have enough data to be useful in the model
columns_to_drop = ['Roof', 'Basement', 'Flooring', 'Exterior']
df = df.drop(columns=columns_to_drop)
print("Columns after dropping:", df.columns.tolist())
print("New shape:", df.shape)

"""Heating has only 14.82% of missing values, so by imputation with the mode, we will fill them with the most common value (scikit-learn developers, 2025)."""

#Fill Heating with the most common value
most_common_heating = df['Heating'].mode()[0]
df['Heating'] = df['Heating'].fillna(most_common_heating)

print("Missing in Heating after fix:", df['Heating'].isnull().sum())
print("Most common heating type used:", most_common_heating)

# Final check to confirm no missing values remain in the columns we're keeping
remaining_nulls = df.isnull().sum()
print(remaining_nulls[remaining_nulls > 0])

#Check duplicate records
duplicates = df.duplicated().sum()
print("Number of duplicate rows:", duplicates)
duplicates = df[df.duplicated()]
duplicates.head(10)

"""
we will remove duplicates and only leave the first occurence for the model not to be distorted with bias (pandas development team, 2024)."""

# Remove duplicate rows, keeping only the first occurrence
df = df.drop_duplicates(keep='first')

# Confirm how many rows remain after removal
print("Rows before:", 44896)
print("Rows after removing duplicates:", len(df))
print("Duplicates removed:", 44896 - len(df))

"""A total of 4,201 duplicate records were identified and deleted from the dataset retaining the first ocurence of each entry. The cleaned dataset contained now 40,695 unique property listings, which will be used for the analysis."""

#Cleaning Checkup and Outlier Detection
# Final verification after all cleaning steps
print("Final Cleaning Set")
print(f"\nTotal rows: {len(df):,}")
print(f"Total columns: {df.shape[1]}")

print("\nMissing values remaining")
nulls = df.isnull().sum()
print(nulls[nulls > 0].sort_values(ascending=False))
if nulls.sum() == 0:
    print("No missing values found")

print("\nOutliers check (Price)")
print(f"Min price:  ${df['Price'].min():,.0f}")
print(f"Max price:  ${df['Price'].max():,.0f}")
print(f"Mean price: ${df['Price'].mean():,.0f}")
print(f"Median price: ${df['Price'].median():,.0f}")

print("\nOutliers check (Square Footage)")
print(f"Min: {df['Square Footage'].min():,.0f} sqft")
print(f"Max: {df['Square Footage'].max():,.0f} sqft")

print("\nOutliers check (Bedrooms)")
print(f"Min: {df['Bedrooms'].min()}")
print(f"Max: {df['Bedrooms'].max()}")

print("\nOutliers check (Bathrooms)")
print(f"Min: {df['Bathrooms'].min()}")
print(f"Max: {df['Bathrooms'].max()}")

print("\nOutliers check (Acreage)")
print(f"Min: {df['Acreage'].min():,.2f} acres")
print(f"Max: {df['Acreage'].max():,.2f} acres")

"""Histograms were created using the matplotlib library to see the distribution of numerical variables and identify potential outliers (Matplotlib Development Team, 2025)."""

#Outlier Visual Analysis
import matplotlib.pyplot as plt
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
fig.suptitle('Distribution of Numerical Variables -Outlier Detection', fontsize=14)
variables = ['Price', 'Square Footage', 'Bedrooms', 'Bathrooms', 'Acreage']
for i, col in enumerate(variables):
    row = i // 3
    col_idx = i % 3
    axes[row, col_idx].hist(df[col], bins=50, color='blue', edgecolor='white')
    axes[row, col_idx].set_title(col)
    axes[row, col_idx].set_xlabel('Value')
    axes[row, col_idx].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""In the histograms we observe that all five numerical variables exhibit strong right skewness, with the major part of the values concentreated near the lower end and a small number of extreme values which extend the distribution to the right.  The extreme values are considered outliers and will be removed using the Interquartile Range (IQR) method.

"""

# Remove extreme outliers using IQR method o numerical variables
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return df[(df[column] >= lower) & (df[column] <= upper)]

rows_before = len(df)

for col in ['Price', 'Square Footage', 'Bedrooms', 'Bathrooms', 'Acreage']:
    df = remove_outliers_iqr(df, col)

print(f"Rows before: {rows_before:,}")
print(f"Rows after:  {len(df):,}")
print(f"Outliers removed: {rows_before - len(df):,}")

#Final Cleaning Check

print("1.SHAPE")
print(f"Rows: {len(df):,}  |  Columns: {df.shape[1]}")

print("\n2.MISSING VALUES")
nulls = df.isnull().sum()
print(nulls[nulls > 0] if nulls.sum() > 0 else "No missing values")

print("\n3.DUPLICATES")
print(f"Duplicate rows: {df.duplicated().sum()}")

print("\n4.DATA TYPES")
print(df.dtypes)

print("\n5. UNIQUE VALUES IN CATEGORICAL COLUMNS")
for col in ['Province', 'Property Type', 'Garage', 'Parking',
            'Fireplace', 'Waterfront', 'Pool', 'Garden', 'Balcony', 'Sewer']:
    print(f"{col}: {df[col].unique()}")

"""Since Bedrooms and Badrooms should be integers and appear as floats, we will change them into integers."""

# Convert Bedrooms and Bathrooms to integers
df['Bedrooms'] = df['Bedrooms'].astype(int)
df['Bathrooms'] = df['Bathrooms'].astype(int)

print(df[['Bedrooms', 'Bathrooms']].dtypes)

"""After completing the dataset cleaning, the final dataset contains 30,972 observations and 19 columns, with no missing values, no duplicate records, and no extreme outliers.  Exploratory Data Analysis and model fitting will be done on the dataset now.

**Exploratory Data Analysis**
During the data cleaning section, the distribution of the Price variable was examined.  The histogram showed a strong right skewness in all numerical variables, which justified removing outliers using the IQR method.  After this, the Price variable will be analyzed in relation with other variables in this section.
"""

# Average Price per Province
import matplotlib.pyplot as plt
province_avg = df.groupby('Province')['Price'].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 5))
plt.bar(province_avg.index, province_avg.values, color='blue', edgecolor='white')
plt.title('Average House Price by Province')
plt.xlabel('Province')
plt.ylabel('Average Price (CAD)')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.tight_layout()
plt.show()

#(Matplotlib Development Team, 2025)

# Boxplot of price per province
plt.figure(figsize=(12, 6))
df.boxplot(column='Price', by='Province',
           patch_artist=True,
           boxprops=dict(facecolor='blue', color='white'),
           medianprops=dict(color='white', linewidth=2))
plt.title('Price Distribution by Province')
plt.xlabel('Province')
plt.ylabel('Price (CAD)')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""As expected, British Columbia and Ontario show the highest housing prices since they consider Vancouver and Toronto cities.  In contrast, provinces like Northern Territories or Saskatchewan show significant lower prices which suggest big regional differences in the Canadian real state market.  Furthermore, the boxplot reveals significative regional price differences.  British Columbia shows the greatest variabilityand the highest prices, reflecting markets as Vancouver.  East provinces and Northern Territories show a more compact distribution with lower mean prices.  As we can see the presence of outliers in almost all provinces suggest that there is a luxury residencial market across the country."""



# Average price per property type
type_avg = df.groupby('Property Type')['Price'].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 5))
plt.bar(type_avg.index, type_avg.values, color='blue', edgecolor='white')
plt.title('Average House Price by Property Type')
plt.xlabel('Property Type')
plt.ylabel('Average Price (CAD)')
plt.xticks(rotation=45, ha='right')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.tight_layout()
plt.show()

"""Duplex and Townhome show the highest average price, which can probably reflect their frequency in markets such as Vancouver or Toronto.  Single Family are located in the middle, while mobile homes and vacant land show the lowest prices, which could be consistent with their low demand as residential properties."""

#Correlation Matrix among numerical variables
# A correlation heatmap was developed among the numeric variables (Waskom, 2021)
import seaborn as sns

numerical_vars = ['Price', 'Square Footage', 'Bedrooms', 'Bathrooms', 'Acreage']
correlation = df[numerical_vars].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation,
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            vmin=-1, vmax=1)
plt.title('Correlation Matrix - Numerical Variables')
plt.tight_layout()
plt.show()

"""Since there are variables which are highly correlated, such as, Bedrooms and Square Footage (0.72) and Bathrooms and Square Footage, a furhter VIF analysis will be run in order to know if Multicollinearity is a problem."""

# Relationship between Square Footage and Price
plt.figure(figsize=(10, 5))
plt.scatter(df['Square Footage'], df['Price'],
            alpha=0.3, color='blue', s=10)
plt.title('Square Footage vs Price')
plt.xlabel('Square Footage (sqft)')
plt.ylabel('Price (CAD)')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.tight_layout()
plt.show()

"""As per the correlation coefficient (0.48) between these two variables, the scatterplot shows a positive relationship since we can see that as the sqft increases, the price tends to increase.  Nevertheless, we can observe a high dispersion in the points of the graph which suggest that the Square Footage by itself does not completely explain the price and that there are other variables that affects it."""

# Relationship between Bedrooms and Price
plt.figure(figsize=(10, 5))
plt.scatter(df['Bedrooms'], df['Price'],
            alpha=0.3, color='blue', s=10)
plt.title('Number of Bedrooms vs Price')
plt.xlabel('Number of Bedrooms')
plt.ylabel('Price (CAD)')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.tight_layout()
plt.show()

"""In contrast with Square Footage, since number of bedrooms is a discrete variable, the relationship with price does not show a linear tendency.  The properties with 3 and 4 bedrooms show the greatest price dispersion, which suggest that by itself this variable is not a strong predictor of price.  This is consistent with a lower correlation between this two variables (0.33)"""

# Relationship between Bathrooms and Price
plt.figure(figsize=(10, 5))
plt.scatter(df['Bathrooms'], df['Price'],
            alpha=0.3, color='blue', s=10)
plt.title('Number of Bathrooms vs Price')
plt.xlabel('Number of Bathrooms')
plt.ylabel('Price (CAD)')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.tight_layout()
plt.show()

"""Just as Bedroom, Bathroom is a discrete variable which can be seen in the scatterplot.  A moderate positive tendency is shown since properties with more bathrooms tend to have higher prices, specially above 3 bathrooms.  This is consistent with the correlation matrix which shows a correlation of 0.45 between these variables.   """

# Relationship between Acreage and Price
plt.figure(figsize=(10, 5))
plt.scatter(df['Acreage'], df['Price'],
            alpha=0.3, color='blue', s=10)
plt.title('Acreage vs Price')
plt.xlabel('Acreage (acres)')
plt.ylabel('Price (CAD)')
plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))
plt.tight_layout()
plt.show()

"""The scatterplot between Acreage and Price shows that most of the properties have small lot sizes, between 0 and 40 acres.  No clear linear tendency is shown between price and acreage which is consistent with a low correlation of 0.13 between these variables.  This suggests that Acreage is not a strong predictor for the variable price in the dataset."""

# Count of Properties per type
property_counts = df['Property Type'].value_counts()
total = len(df)

fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.bar(property_counts.index, property_counts.values,
              color='blue', edgecolor='white')
ax.set_title('Number of Properties by Type')
ax.set_xlabel('Property Type')
ax.set_ylabel('Count')
plt.xticks(rotation=45, ha='right')

for bar, count in zip(bars, property_counts.values):
    percentage = (count / total) * 100
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 100,
            f'{percentage:.1f}%',
            ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

"""The dataset consists mostly of single family and condos which account for 84.6% of the total properties.  The least common of the properties are vacant land, multifamily, and mobile home, wich have few observations and might limit the ability of the model to predict prices for these types of properties."""

# Average price per amenities
amenities = ['Garage', 'Parking', 'Fireplace', 'Waterfront', 'Pool']
avg_prices = [df[df[amenity] == 'Yes']['Price'].mean()
              for amenity in amenities]

fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.bar(amenities, avg_prices, color='blue', edgecolor='white')
ax.set_title('Average Price by Amenity')
ax.set_xlabel('Amenity')
ax.set_ylabel('Average Price (CAD)')
ax.yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M'))

for bar, price in zip(bars, avg_prices):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 5000,
            f'${price/1e6:.2f}M',
            ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

"""Properties with fireplace showed the highest average price, followed by garage and waterfront.  Even when it was expected that waterfront properties would be the highest, its average prices are similar to parking and pool amenities,which could possibly be due to the reduced subset of the sample after the data cleaning.

**Multiple Linear Regression**
"""

# Change binary variables Yes/No into numbers 1/0
binary_cols = ['Garage', 'Parking', 'Fireplace', 'Waterfront', 'Pool', 'Garden', 'Balcony']
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

print("Binary variables:")
print(df[binary_cols].head())

"""In the case of variables with multiple categories (i.e. Province) we will use One Hot Encoding to convert them into numeric variables (Scikit-learn developers, 2025)."""

# One Hot Encoding for multiple categories variables(pandas development team,2024)
df_model = pd.get_dummies(df, columns=['Province', 'Property Type', 'Heating', 'Sewer'], drop_first=True)
print("Shape before:", df.shape)
print("Shape after:", df_model.shape)
print("\nNew columns created:")
print(df_model.columns.tolist())

"""For the model and after our data cleanup and the exploratory data analysis, three variables will be droped.  City was excluded due to its high cardinality and the presence of many unique factors.  Applying One Hot Encoding to this variable would generate hundreds of additional columns which could generate model overfitting and poor predictions over our dataset (James, 2023).  Additionally, Latitud and Longitude were excluded because the geographic location is already captured by the Province variable.  Including these variables would introduce noise into the model without adding predictive power to the linear regression model.


"""

from sklearn.model_selection import train_test_split

# Excluding variables that will not be part of the model
X = df_model.drop(columns=['Price', 'City', 'Latitude', 'Longitude'])
y = df_model['Price']

# Dividir en 80% entrenamiento y 20% prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print(f"Total Observations: {len(X):,}")
print(f"Training: {len(X_train):,} (80%)")
print(f"Testing:        {len(X_test):,} (20%)")

from sklearn.linear_model import LinearRegression

# Training of the Multiple Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

# Making predictions with the testing set
y_pred = model.predict(X_test)

print("Model trained")
print(f"Number of variables used: {X_train.shape[1]}")

from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.api as sm
import numpy as np

# Sklearn evaluation
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = np.mean(np.abs(y_test - y_pred))

print("Model Evaluation")
print(f"R²:    {r2:.4f}")
print(f"RMSE:  ${rmse:,.2f}")
print(f"MAE:   ${mae:,.2f}")
print(f"Average Price in Testing: ${y_test.mean():,.2f}")
print(f"RMSE as a % of Price:  {rmse/y_test.mean()*100:.1f}%")

# ANOVA
X_train_sm = sm.add_constant(X_train.astype(float))
model_sm = sm.OLS(y_train.astype(float), X_train_sm).fit()
print(model_sm.summary())

"""The multiple linear regression model has a R2 of 0.61, explaining 60% of the variation in price.  Additionaly, Significant F has a p-value of 0.00 confirmating that the model is statitistically significant.  The variables with the greatest impact are Square Footage, Bathrooms, Bedrooms and the property location per province.  Nevertheless, the model shows moderate multicolliniarity which is a limitation for the coefficient interpretation.
After looking at the regression results, and clearly identifying variables such as Fireplace, Pool or Garden which are statistically not significant to the model, Backward Elimination was applied (James, 2023).
"""

#Backward Elimination - remove variables with p-values > 0.05
import statsmodels.api as sm
def backward_elimination(X, y, significance=0.05):
    cols = list(X.columns)
    while True:
        X_sm = sm.add_constant(X[cols].astype(float))
        model = sm.OLS(y.astype(float), X_sm).fit()
        p_values = model.pvalues[1:]  # exclude the intercept
        max_p = p_values.max()
        if max_p > significance:
            removed = p_values.idxmax()
            print(f"Eliminando: {removed} (p-value: {max_p:.4f})")
            cols.remove(removed)
        else:
            break
    return cols, model

final_cols, final_model = backward_elimination(X_train, y_train)

print(f"\nFinal Variables: {len(final_cols)}")
print(f"\nFinal Model Summary:")
print(final_model.summary())

# Final Model ANOVA
print(f"\nFinal Model ANOVA")
print(f"F-statistic:  {final_model.fvalue:.4f}")
print(f"p-value:      {final_model.f_pvalue:.6f}")
print(f"R2:           {final_model.rsquared:.4f}")
print(f"Adjusted R2:  {final_model.rsquared_adj:.4f}")
print(f"Obervations: {int(final_model.nobs):,}")

"""Through Backward Elimination 14 Variables were removed from the model since their p-values were greater than 0.05 (James et al., 2023). The final model now consists of 27 variables which are statistically significant.  The R2 remained in 0.61 while statistic F increased from 944 to 1,433 which talks about a more efficient and parsimonious model.
Nevertheless, there seem to be multicollinearity among the variables, so VIF will be used to corroborate (Hair et al., 2019).
"""

# Final Model VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

X_final = X_train[final_cols].astype(float)

vif_final = pd.DataFrame()
vif_final['Variable'] = final_cols
vif_final['VIF'] = [variance_inflation_factor(X_final.values, i)
                    for i in range(len(final_cols))]

vif_final = vif_final.sort_values('VIF', ascending=False)
print(vif_final.to_string(index=False))

"""The model's VIF analysis reveals that Square Footage, Bedrooms and Bathrooms have VIF values greater than 10, which indicateds moderate to high multicollinearity among these variables (Hair et al., 2019).  This could be expected since as property footage increases, properties tend to have more bedrooms and bathrooms.  We will test the model without the variable Bedrooms, since it has the lowest correlation with price, in order to find out if Square Footage and Bathroom's VIF decreases and the total model R2 increases."""

# Test the model without Bedrooms
final_cols_no_bed = [col for col in final_cols if col != 'Bedrooms']

X_no_bed = X_train[final_cols_no_bed].astype(float)

# VIF without Bedrooms
vif_no_bed = pd.DataFrame()
vif_no_bed['Variable'] = final_cols_no_bed
vif_no_bed['VIF'] = [variance_inflation_factor(X_no_bed.values, i)
                     for i in range(len(final_cols_no_bed))]

print("VIF without Bedrooms:")
print(vif_no_bed[vif_no_bed['Variable'].isin(['Square Footage', 'Bathrooms', 'Bedrooms'])] \
      .sort_values('VIF', ascending=False).to_string(index=False))

# R² wihtout Bedrooms
model_no_bed = sm.OLS(y_train.astype(float),
                      sm.add_constant(X_no_bed)).fit()
print(f"\nR² without Bedrooms:  {model_no_bed.rsquared:.4f}")
print(f"R2 Final Model:  {final_model.rsquared:.4f}")
print(f"Difference:       {final_model.rsquared - model_no_bed.rsquared:.4f}")

"""The results showed that even when removing the variable Bethroom, Square Footage and Bathroom's VIF marginally decreased, but are still above the 10 threshold.  Furthermore, the model's R2 decreased 0.0004 points, so we decided to keep the variable and acknowledge multicollinearity among these variables as a limitation to the model due to the nature of the industry where footage, bedrooms and bathrooms are structurally correlated."""

import matplotlib.pyplot as plt
import numpy as np

# Predictions with Final Model
X_test_final = X_test[final_cols].astype(float)
y_pred_final = final_model.predict(sm.add_constant(X_test_final.astype(float)))

#Residuals
residuals = y_test - y_pred_final

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Regression Diagnostic Plots', fontsize=14)

# Graph 1 - Real vs. Predicted
axes[0].scatter(y_test, y_pred_final, alpha=0.3, color='blue', s=10)
mn = min(y_test.min(), y_pred_final.min())
mx = max(y_test.max(), y_pred_final.max())
axes[0].plot([mn, mx], [mn, mx], 'r--', linewidth=1.5)
axes[0].set_title('Actual vs Predicted')
axes[0].set_xlabel('Actual Price')
axes[0].set_ylabel('Predicted Price')

# Graph 2 - Residuals vs. Predicted
axes[1].scatter(y_pred_final, residuals, alpha=0.3, color='blue', s=10)
axes[1].axhline(0, color='red', linewidth=1.5, linestyle='--')
axes[1].set_title('Residuals vs Predicted')
axes[1].set_xlabel('Predicted Price')
axes[1].set_ylabel('Residuals')

# Graph 3 - Residuals Histogram
axes[2].hist(residuals, bins=50, color='blue', edgecolor='white')
axes[2].set_title('Distribution of Residuals')
axes[2].set_xlabel('Residual')
axes[2].set_ylabel('Frequency')

# Visual comparison between real and predicted prices
# We took a sample of 100 properties for visualization purposes
sample_idx = np.arange(100)

plt.figure(figsize=(14, 5))
plt.plot(sample_idx, y_test.values[:100]/1e6,
         color='blue', linewidth=1.5, label='Actual Price')
plt.plot(sample_idx, y_pred_final[:100]/1e6,
         color='red', linewidth=1.5, linestyle='--', label='Predicted Price')
plt.title('Actual vs Predicted Housing Prices (Sample of 100 Properties)')
plt.xlabel('Property Index')
plt.ylabel('Price (Millions CAD)')
plt.legend()
plt.tight_layout()
plt.show()

plt.tight_layout()
plt.show()

"""**Regression Diagnostics Plots**
These graphs help us to evaluate the linear regression assumptions.  First, the Actual vs. Predicted graph shows a clear linear tendency, which supports the linearity assumption in the model.  Nevertheless, it shows a greater dispersion among properties with high prices suggesting that the model predicts best low to medium price ranges.  Second, the Residual vs.Predicted reveals a funnel pattern, suggesting a mild heteroscedasticity since the spread of residuals increases for higher predicted values (Statistics By Jim, 2025).  This indicates that prediction errors are larger for expensive properties.  Nevertheless, it should not be considered a severe case and does not substantially affect the overall usefulness of the model. Third, the histogram of residuals shows an approxiamate normal distribution with some positive assymetry and partially covering the normality assumption (Hunter, 2007).
Furthermore, the Actual vs. Predicted Housing Prices with a sample of 100 properties reveals that the model closely follows the general price tendency.  Both the blue and the red lines are close to each otherin properties with middle prices; nevertheless the greatest deviations occur in extreme prices.  This confirms that the model is more reliable on predicting properties in the regular price range of the Canadian market (Harris et al., 2020).
"""

# Calcular ambos sobre el mismo set de prueba
r2_final = r2_score(y_test, y_pred_final)
n = len(y_test)
k = len(final_cols)
adj_r2_final = 1 - (1 - r2_final) * (n - 1) / (n - k - 1)

print("FINAL MODEL EVALUATION")
print(f"R²:                {r2_final:.4f}")
print(f"Adjusted R²:       {adj_r2_final:.4f}")
print(f"RMSE:              ${rmse_final:,.2f}")
print(f"MAE:               ${mae_final:,.2f}")
print(f"Average Price:     ${y_test.mean():,.2f}")
print(f"RMSE as % of avg:  {rmse_final/y_test.mean()*100:.1f}%")
print(f"F-statistic:       {final_model.fvalue:.2f}")
print(f"p-value (F):       {final_model.f_pvalue:.6f}")
print(f"Variables in model:{len(final_cols)}")

"""The final Multiple Regression Model obtained through Backward Elimination have 27 variables which are statistically significant and explains 60.5% of the  properties' price deviation (R2=0.605).  Adjusted R2 (0.603) confirms that the model is not overfitted and the Statistical F with p-value 0.000 indicates the overal statistical significance of the model.  Besides, an RMSE of $312,921.74 represents 40.6% of the average price, and reflects the Canadian real estate market complexity, where factors not included in this dataset (i.e. the property condition, neiborhood, market tendencies) also influence the price."""